### ISSUE TITLE
no work in tablet  lenovo

### ISSUE THREAD

**Issue by MohtashamVahid** [omidheshmatinia/RippleValidatorEditText#1]
سلام امید جان
این برای من تو تبلت لنوو کار نکرد و  اصلا  چیزی داخلش تایپ نمیشه.
ممنون

tablet lenovo 
android 5.1

**Comment by omidheshmatinia** [comment]
مشکلش به خاطر
hardware acceleration 
بود 
اکی شد در ورژن 0.8.01

**Comment by MohtashamVahid** [comment]
ی دونه ای امید جان . 
ممنون
